org: asr101
app: data-scraper-app
service: dataScraperSync
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  data-scraper-sync:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
